DEFINE TABLESPACE_NAME = &&1
DEFINE END_DATA = '_DATA'

PROMPT 'Creating row data table'
--BEGIN
--   EXECUTE IMMEDIATE 'DROP TABLE raw_data';
--EXCEPTION
--   WHEN OTHERS THEN
--      IF SQLCODE != -942 THEN
--         RAISE;
--      END IF;
--END;

 CREATE TABLE RAW_DATA (
    "FIRST_NAME" VARCHAR2(225), 
	"LAST_NAME" VARCHAR2(225), 
	"NICKNAME" VARCHAR2(225), 
	"EMAIL" VARCHAR2(225), 
	"PLAYLIST_NAME" VARCHAR2(225), 
	"PLAYLIST_TYPE" VARCHAR2(6), 
	"MUSIC_TYPE" VARCHAR2(225), 
	"COMPOSITION_NAME" VARCHAR2(225), 
	"LENGTH" NUMBER(38), 
	"OWNER_FIRST_NAME" VARCHAR2(225), 
	"OWNER_LAST_NAME" VARCHAR2(225), 
	"OWNER_NICKNAME" VARCHAR2(225), 
	"LIKED" VARCHAR2(3), 
	"COMPOSITION_LIKES" NUMBER(38,0), 
	"LISTEN" NUMBER, 
	"COMMENTS_TRACK" VARCHAR2(2048), 
	"CURRENT_LISTENING" VARCHAR2(1), 
	"STOPPED_TIME" NUMBER
) 
TABLESPACE &&TABLESPACE_NAME&&END_DATA;
PROMPT 'Raw data table was created'

PROMPT 'Inserting raw data'
Insert into RAW_DATA (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,LENGTH,OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,LIKED,COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Владислав','Кисляков','Chewbaca','ChewbacaMorning@gmail.com','Morning','User','Electronic','Nicolas Jaar - El Bandido','397','Oleg','Synytsky','Dreamboat','yes','2126','108000','Nah not feelin it',null,null);
Insert into RAW_DATA (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,LENGTH,OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,LIKED,COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Владислав','Кисляков','Chewbaca','ChewbacaMorning@gmail.com','Morning','User','Electronic','Electro - Trance - House','249','Oleg','Synytsky','Dreamboat','no','4005','5055',null,null,null);
Insert into RAW_DATA (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,LENGTH,OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,LIKED,COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Владислав','Кисляков','Chewbaca','ChewbacaMorning@gmail.com','Morning','User','Electronic','Nice Night','321','Oleg','Synytsky','Dreamboat','yes','88','82000','NIGGER!!!!','Y','62');
Insert into RAW_DATA (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,LENGTH,OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,LIKED,COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Владислав','Кисляков','Chewbaca','ChewbacaMorning@gmail.com','Morning','User','Electronic','Electro 2020','605','Christian','Radaelli','Dumpling','no','231','99548','Sadie is my dog',null,null);
Insert into RAW_DATA (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,LENGTH,OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,LIKED,COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Владислав','Кисляков','Chewbaca','ChewbacaMorning@gmail.com','Morning','User','Electronic','REMIX BOLICHEROS 2019!!!','481','Christian','Radaelli','Dumpling','yes','84','32001',null,null,null);
Insert into RAW_DATA (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,LENGTH,OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,LIKED,COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Sport','System','Sport','Drifting','131','Ten','Walls','Monsieur','no','34','806','Jesus christ',null,null);
Insert into RAW_DATA (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,LENGTH,OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,LIKED,COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Sport','System','Sport','SESSION #186 (Feat. Ten Walls)','242','Ten','Walls','Monsieur','yes','456','1050',null,null,null);
Insert into RAW_DATA (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,LENGTH,OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,LIKED,COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Sport','System','Pop','Ariana Grande - Side To Side Ft. Nicki Minaj (Remix)','192','Kelvin','Pasman','Snuggy','no','1102','1526','another classic',null,null);
Insert into RAW_DATA (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,LENGTH,OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,LIKED,COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Sport','System','Pop','Major Lazer - Too Original (Remix)','165','Kelvin','Pasman','Snuggy','yes','358','1200','адский разгон',null,null);
Insert into RAW_DATA (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,LENGTH,OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,LIKED,COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Sport','System','Sport','Ten Walls - Sparta','224','Ten','Walls','Monsieur','no','88','22000','Очень серьезный кач','Y','121');
Insert into RAW_DATA (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,LENGTH,OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,LIKED,COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Bamboo','User','Chill','Murda On They Mind (Tales From Mount Zion)','182',null,null,'DJ Bishop','yes','3306','540050',null,null,null);
Insert into RAW_DATA (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,LENGTH,OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,LIKED,COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Bamboo','User','Electronic','James Blake - Air Lack Thereof','249','H?lder','Leal','Hotshot','no','4455','1433',null,null,null);
Insert into RAW_DATA (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,LENGTH,OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,LIKED,COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Bamboo','User','Electronic','Little Fish','133','H?lder','Leal','Hotshot','yes','6587','8890',null,null,null);
Insert into RAW_DATA (FIRST_NAME,LAST_NAME,NICKNAME,EMAIL,PLAYLIST_NAME,PLAYLIST_TYPE,MUSIC_TYPE,COMPOSITION_NAME,LENGTH,OWNER_FIRST_NAME,OWNER_LAST_NAME,OWNER_NICKNAME,LIKED,COMPOSITION_LIKES,LISTEN,COMMENTS_TRACK,CURRENT_LISTENING,STOPPED_TIME) values ('Елизавета','Рапинчук','Bug','Circle_Bug@gmail.com','Bamboo','User','Electronic','Jamie XX - Loud Places (feat. Romy)','283','H?lder','Leal','Hotshot','no','2201','202023',null,null,null);
PROMPT 'Row data was inserted'

UNDEFINE TABLESPACE_NAME
UNDEFINE END_DATA