DEFINE USER_NAME = &&1
DEFINE END_DATA = '_DATA'
DEFINE END_INDEX = '_INDEX'

PROMPT 'Creating user'

CREATE USER &USER_NAME IDENTIFIED BY oracle
       DEFAULT TABLESPACE &USER_NAME&END_DATA
       TEMPORARY TABLESPACE temp
       QUOTA UNLIMITED ON &USER_NAME&END_DATA
	   QUOTA UNLIMITED ON &USER_NAME&END_INDEX;
       
PROMPT 'User was created'

UNDEFINE USER_NAME
UNDEFINE END_DATA
UNDEFINE END_INDEX