DEFINE USER_NAME = &&1

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE ANY TABLE, CREATE ANY VIEW, CREATE TYPE,
      CREATE PROCEDURE, CREATE SYNONYM, CREATE TRIGGER, CREATE SEQUENCE, CREATE MATERIALIZED VIEW, QUERY REWRITE
      TO &USER_NAME;

UNDEFINE USER_NAME