DEFINE TABLESPACE_NAME = &&1
DEFINE END_DATA = '_DATA'
DEFINE END_INDEX = '_INDEX'

CREATE TABLE album (
  ID INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOMAXVALUE NOT NULL
, title VARCHAR2(255) NOT NULL 
, CONSTRAINT album_pk PRIMARY KEY (
    ID
  )
  USING INDEX (
      CREATE UNIQUE INDEX album_pk ON album(ID)
	  TABLESPACE &&TABLESPACE_NAME&&END_INDEX
  )
)
TABLESPACE &&TABLESPACE_NAME&&END_DATA;

COMMENT ON COLUMN album.ID IS 'Primary key';

COMMENT ON COLUMN album.title IS 'Title of album';

UNDEFINE TABLESPACE_NAME
UNDEFINE END_DATA
UNDEFINE END_INDEX