DEFINE TABLESPACE_NAME = &&1
DEFINE END_DATA = '_DATA'
DEFINE END_INDEX = '_INDEX'

CREATE TABLE repost_song (
  ID_user INT NOT NULL
, ID_song INT NOT NULL
)
TABLESPACE &&TABLESPACE_NAME&&END_DATA;

ALTER TABLE repost_song ADD CONSTRAINT fk_repost_song_ID_user FOREIGN KEY(ID_user)
REFERENCES "user" (ID);

ALTER TABLE repost_song ADD CONSTRAINT fk_repost_song_ID_album FOREIGN KEY(ID_song)
REFERENCES song (ID);

CREATE INDEX fk_repost_song_ID_user ON repost_song(ID_user) TABLESPACE &&TABLESPACE_NAME&&END_INDEX;

CREATE INDEX fk_repost_song_ID_album ON repost_song(ID_song) TABLESPACE &&TABLESPACE_NAME&&END_INDEX;

COMMENT ON COLUMN repost_song.ID_user IS 'Primary key of user';

COMMENT ON COLUMN repost_song.ID_song IS 'Primary key of song';

UNDEFINE TABLESPACE_NAME
UNDEFINE END_DATA
UNDEFINE END_INDEX