DEFINE TABLESPACE_NAME = &&1
DEFINE END_DATA = '_DATA'
DEFINE END_INDEX = '_INDEX'
DEFINE END_INDEX = '_INDEX'

CREATE TABLE song (
  ID INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOMAXVALUE NOT NULL
, ID_album INT
, title VARCHAR2(255) NOT NULL 
, "duration" INT NOT NULL
, ID_user INT NOT NULL
, CONSTRAINT song_pk PRIMARY KEY (
    ID
  )
  USING INDEX (
      CREATE UNIQUE INDEX song_pk ON song(ID)
	  TABLESPACE &&TABLESPACE_NAME&&END_INDEX
  )
)
TABLESPACE &&TABLESPACE_NAME&&END_DATA;

ALTER TABLE song ADD CONSTRAINT fk_song_ID_album FOREIGN KEY(ID_album)
REFERENCES album (ID);

CREATE INDEX fk_song_ID_album ON song(ID_album) TABLESPACE &&TABLESPACE_NAME&&END_INDEX;

ALTER TABLE song ADD CONSTRAINT fk_song_ID_user FOREIGN KEY(ID_user)
REFERENCES "user" (ID);

CREATE INDEX fk_song_ID_user ON song(ID_user) TABLESPACE &&TABLESPACE_NAME&&END_INDEX;

COMMENT ON COLUMN song.ID IS 'Primary key';

COMMENT ON COLUMN song.ID_album IS 'Primary key of album';

COMMENT ON COLUMN song.Title IS 'Title of song';

COMMENT ON COLUMN song."duration" IS 'Duration of song';

COMMENT ON COLUMN song.ID_user IS 'Primary key of creator';



ALTER TABLE "user" ADD CONSTRAINT fk_user_ID_song FOREIGN KEY(ID_song)
REFERENCES song (ID);

CREATE INDEX fk_user_ID_song ON "user"(ID_song) TABLESPACE &&TABLESPACE_NAME&&END_INDEX;

UNDEFINE TABLESPACE_NAME
UNDEFINE END_DATA
UNDEFINE END_INDEX